server:
  port: 8080

spring:
  application:
    name: demo-app

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  output:
    ansi:
      enabled: always

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo_app.model
  configuration:
    map-underscore-to-camel-case: true

langchain4j:
  open-ai:
    chat-model:
      base-url: ${OPENAI_BASE_URL}
      api-key: ${OPENAI_API_KEY}
      model-name: ${OPENAI_MODEL}
